Ucc/Ucc/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^matriculas/', include('matriculas.urls')),
]

Ucc/matriculas/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy

from matriculas.views import (
    AlumnoList,
    AlumnoCreate,
    AlumnoDetail,
    CursoList,
    IndexPageView,
    CursoCreate,
    MatriculaCreate,
    AlumnoUpdate,
    AlumnoDelete
)

urlpatterns = [
    url(
        r'alumno/$',
        AlumnoList.as_view(),
        name='alumno'
        ),
    url(
        r'^(?P<pk>\d+)/$',
        AlumnoUpdate.as_view(),
        name='actualizar-alumno'
        ),
    url(
        r'^eliminar/(?P<pk>\d+)/$',
        AlumnoDelete.as_view(),
        name='eliminar-alumno'
        ),
    url(
        r'^login/$',
        LoginView.as_view(
            template_name='matriculas/login.html'
            ),
        name='login'
        ),
    url(
        r'^logout/$',
        LogoutView.as_view(next_page=reverse_lazy('login')),
        name='logout'
    ),
    url(
        r'index/$',
        IndexPageView.as_view(),
        name='index'),
    url(
        r'^crear-alumnos/$',
        AlumnoCreate.as_view(),
        name='crear-alumnos'
    ),
    url(
        r'^detalles/(?P<pk>\d+)/$',
        AlumnoDetail.as_view(),
        name='detail'
    ),
    url(
        r'curso/$',
        CursoList.as_view(),
        name=''
        ),
    url(
        r'^crear-cursos/$',
        CursoCreate.as_view(),
        name='crear-cursos'
        ),
    url(
        r'^crear-matricula/$',
        MatriculaCreate.as_view(),
        name='realizar-matricula'
        )
]

Ucc/matriculas/models.py
from django.db import models


class Alumno(models.Model):
    nombres = models.CharField(max_length=40)
    primer_apellido = models.CharField(max_length=30)
    segundo_apellido = models.CharField(max_length=30)
    cedula = models.CharField(max_length=10)
    sexos = (('F', 'Femenino'), ('M', 'Masculino'))
    sexo = models.CharField(max_length=1, choices=sexos, default='M')
    ciudad_nacimiento = models.CharField(max_length=40)

    def NombreCompleto(self):
        cadena = "{0} {1} {2}"
        return cadena.format(
            self.nombres,
            self.primer_apellido,
            self.segundo_apellido
            )

    def __str__(self):
        return self.NombreCompleto()


class Curso(models.Model):
    nombre = models.CharField(max_length=40)
    creditos = models.PositiveSmallIntegerField()
    estado = models.BooleanField(default=True)

    def __str__(self):
        return "{0} ({1})".format(self.nombre, self.creditos)


class Matricula(models.Model):
    alumno = models.ForeignKey(
        Alumno,
        null=False,
        blank=False,
        on_delete=models.CASCADE
        )
    curso = models.ForeignKey(
        Curso,
        null=False,
        blank=False,
        on_delete=models.CASCADE
        )
    fecha_matricula = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        cadena = "{0} => {1}"
        return cadena.format(self.Alumno, self.Curso)

Ucc/matriculas/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView
from django.core.urlresolvers import reverse_lazy
from django. contrib.auth.mixins import LoginRequiredMixin

from matriculas.models import Alumno, Curso, Matricula


class AlumnoList(LoginRequiredMixin, ListView):
    model = Alumno
    fields = ['nombres']
    context_object_name = 'matriculas'
    template_name = 'matriculas/alumno_lista.html'


class AlumnoUpdate(LoginRequiredMixin, UpdateView):
    model = Alumno
    fields = ['nombres', 'primer_apellido', 'segundo_apellido']
    template_name = 'matriculas/actualizar_alumnos.html'
    success_url = reverse_lazy('alumno')


class AlumnoDelete(LoginRequiredMixin, DeleteView):
    model = Alumno
    template_name = 'matriculas/eliminar-alumnos.html'
    success_url = reverse_lazy('alumno')


class AlumnoCreate(LoginRequiredMixin, CreateView):
    model = Alumno
    fields = [
        'nombres',
        'primer_apellido',
        'segundo_apellido',
        'cedula',
        'sexo',
        'ciudad_nacimiento'
    ]
    template_name = 'matriculas/crear-alumnos.html'
    success_url = reverse_lazy('alumno')


class AlumnoDetail(LoginRequiredMixin, DetailView):
    model = Alumno
    template_name = 'matriculas/alumnos_datails.html'


class CursoList(LoginRequiredMixin, ListView):
    model = Curso
    context_object_name = 'matriculas'


class CursoCreate(LoginRequiredMixin, CreateView):
    model = Curso
    fields = [
        'nombre',
        'creditos',
        'estado'
    ]
    template_name = 'matriculas/crear-cursos.html'
    success_url = reverse_lazy('crear-cursos')


class MatriculaCreate(LoginRequiredMixin, CreateView):
    model = Matricula
    fields = [
        'alumno',
        'curso'
    ]
    template_name = 'matriculas/realizar-matricula.html'
    success_url = reverse_lazy('realizar-matricula')


class IndexPageView(LoginRequiredMixin, TemplateView):
    template_name = "matriculas/index.html"

Ucc/matriculas/templates/matriculas/actualizar_alumnos.html
{% extends 'matriculas/base.html' %}

{% block titulo %}
  <h2>Modificar alumno - UCC</h2>
{% endblock %}
{% block contenido %}
      {% csrf_token %}
      <div style="margin-left:400px;">
        {{ form.as_p }}
      </div>
      <br>
      <input type="submit" value="Update" class="btn btn-generico" style="margin-left:430px;"/>
      <a href="{% url "alumno" %}"><button type="button"  class="btn btn-generico">Regresar</button></a>
{% endblock %}

Ucc/matriculas/templates/matriculas/alumno_lista.html
{% extends 'matriculas/base.html' %}
{% block titulo %}
  <h2>Listados de alumnos - UCC</h2>
{% endblock %}
{% block contenido %}
{% csrf_token %}
<div class="tablaResultados col-xs-12">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>CEDULA</th>
                <th>NOMBRES</th>
                <th>&nbsp;</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        {% for alumno in matriculas %}
        <tbody>
            <tr>
                <td><a href="{% url "detail" alumno.id %}">{{ alumno.id }}</a></td>
                <td>{{ alumno.cedula }}</td>
                <td>{{ alumno.NombreCompleto }}</td>
                <td><a href="{% url "actualizar-alumno" alumno.id %}">Editar</a></td>
                <td><a href="{% url "eliminar-alumno" alumno.id %}">Eliminar</a></td>
                <!-- <th><a href="#" title="Editar" class="btnEdit" data-toggle="modal" data-target="#myModal2"  onkeyup="copiar()"></a></th>
                <th><a href="#" title="Eliminar" class="btnRemove" data-toggle="modal" data-target="#myModal3"></th> -->
            </tr>
        </tbody>
        {% endfor %}
    </table>
</div><!-- TABLA RESULTADOS -->
  <a href="{% url "index" %}"><button type="button"  class="btn btn-generico" style="margin-left:430px;">Regresar</button></a>
  <a href="{% url 'crear-alumnos' %}"><button type="button"  class="btn btn-generico">Crear alumno</button></a>
{% endblock %}

Ucc/matriculas/templates/matriculas/alumnos_datails.html
{% extends 'matriculas/base.html' %}

{% block titulo %}
  <h2>Detalles de matricula - UCC</h2>
{% endblock %}
{% block contenido %}
  <h4>Datos del alumno:</h4>
  <hr>
  <div class="tablaResultados col-xs-12">
      <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>NOMBRE</th>
                <th>PRIMER APELLIDO</th>
                <th>SEGUNDO APELLIDO</th>
                <th>CEDULA</th>
                <th>SEXO</th>
                <th>CIUDAD DE NACIMIENTO</th>
            </tr>
        </thead>
        <tbody>
        <tr>
          <td>{{ alumno.nombres }}</td>
          <td>{{ alumno.primer_apellido }}</td>
          <td>{{ alumno.segundo_apellido }}</td>
          <td>{{ alumno.cedula }}</td>
          <td>{{ alumno.sexo }}</td>
          <td>{{ alumno.ciudad_nacimiento }}</td>
        </tr>
        </tbody>
      </table>
        <br>
  </div>
  <br>
  <h4>Materias matriculadas:</h4>
  <hr>
  <div class="tablaResultados col-xs-12">
    <table class="table table-striped table-hover">
      <thead>
          <tr>
              <th>ID</th>
              <th>NOMBRE</th>
              <th>CREDITOS</th>
              <th>ESTADO</th>
          </tr>
      </thead>
      {% for matricula in alumno.matricula_set.all %}
      <tbody>
        <tr>
          <td>{{ matricula.curso.id }}</td>
          <td>{{ matricula.curso.nombre }}</td>
          <td>{{ matricula.curso.creditos }}</td>
          <td>{{ matricula.curso.estado }}</td>
        </tr>
      </tbody>
      {% endfor %}
    </table>
    <br>
  <a href="{% url "alumno" %}"><button type="button"  class="btn btn-generico"style="margin-left:350px;">Regresar</button></a>
  <a href="{% url "crear-alumnos" %}"><button type="button"  class="btn btn-generico">Crear alumno</button></a>
  <a href="{% url "index" %}"><button type="button"  class="btn btn-generico">Ir a Home</button></a>
</div>
{% endblock %}

Ucc/matriculas/templates/matriculas/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="es">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Matriculas - UCC</title>
  <!-- CSS  -->
  <link href="{% static 'matriculas/' %}css/bootstrap.min.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'matriculas/' %}css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body>
  <div class="section catalogo">
    <div class="container">
    <div class="logos">
      <div class="row headerContainer">
        <div class="col-xs-12">
          <div class="logo-catalogo">
          </div>
        </div>
      </div>
    </div>

    <div class="container-catalogo z-depth-4">
      <div class="row">
        <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10 titulo">
          {% block titulo %}

          {% endblock %}
        </div>
        <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2">
          <a href="#" class="btn-salir" data-toggle="modal" data-target="#myModal3">Cerrar sesión</a>
        </div>
      </div>
      <div class="row">
        <div class="form-catalogo btnInicio clearfix">
          <form class="" action="" method="post">
            {% block contenido %}
            {% endblock %}
          </form>
        </div>
      </div>
      <div class="sheet2 hide-on-small-only"></div>
    </div> <!-- CONTAINER CATÁLOGO -->

    </div> <!-- CONTAINER -->
  </div>
  <!--  Scripts-->

  <div id="myModal3" class="modal fade" role="dialog">
      <div class="modal-dialog">
          <!-- Modal content-->
          <div class="modal-content">
              <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">Salir de la aplicación</h4>
              </div>
              <div class="modal-body">
                  <h3>¿Confirma que desea salir de la aplicación?</h3>
              </div>
              <div class="modal-footer">
                  <a href="{% url "logout" %}"><button type="button" class="btn btn-generico">Aceptar</button></a>
                  <button type="button" class="btn btn-generico" data-dismiss="modal">Cancelar</button>
              </div>
          </div>
      </div>
  </div>

  <script src="{% static 'matriculas/' %}js/jquery-2.1.1.min.js"></script>
  <script src="{% static 'matriculas/' %}js/bootstrap.min.js"></script>
  <script src="{% static 'matriculas/' %}js/init.js"></script>

  </body>
</html>

Ucc/matriculas/templates/matriculas/crear-alumnos.html
{% extends 'matriculas/base.html' %}

{% block titulo %}
  <h2>Crear alumno - UCC</h2>
{% endblock %}
{% block contenido %}
  {% csrf_token %}
  <div style="margin-left:400px;">
    {{ form.as_p }}
  </div>
  <input type="submit" name="" value="Crear"  class="btn btn-generico" style="margin-left:430px;">
  <a href="{% url "index" %}"><button type="button"  class="btn btn-generico">Regresar</button></a>
{% endblock %}

Ucc/matriculas/templates/matriculas/crear-cursos.html
{% extends 'matriculas/base.html' %}

{% block titulo %}
  <h2>Crear cursos - UCC</h2>
{% endblock %}
{% block contenido %}
  {% csrf_token %}
  <div style="margin-left:400px;">
    {{ form.as_p }}
  </div>
  <input type="submit" name="" value="Crear"  class="btn btn-generico" style="margin-left:430px;">
  <a href="{% url "index" %}"><button type="button"  class="btn btn-generico">Regresar</button></a>
{% endblock %}

Ucc/matriculas/templates/matriculas/eliminar-alumnos.html
{% extends 'matriculas/base.html' %}

{% block titulo %}
  <h2>Eliminar alumno - UCC</h2>
{% endblock %}
{% block contenido %}
      {% csrf_token %}
      <h2 style="text-align: center;">Esta seguro que desea eliminar al alumnos "{{ object }}"?</h2>
      <input type="submit" value="Aceptar" class="btn btn-generico"style="margin-left:400px;"/>
      <a href="{% url "alumno" %}"><button type="button"  class="btn btn-generico" >Regresar</button></a>
{% endblock %}

Ucc/matriculas/templates/matriculas/index.html
{% extends 'matriculas/base.html' %}

Opciones - Matriculas UCC
{% block titulo %}
  <h2>Opciones - Matriculas UCC</h2>
{% endblock %}
{% block contenido %}
  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
      <a href="{% url 'realizar-matricula' %}" class="btnConsultar"></a>
      <a href="{% url 'crear-alumnos' %}" class="btnNuevo"></a>
  </div>
  <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
      <a href="{% url 'crear-cursos' %}" class="btnCursos"></a>
      <a href="{% url 'alumno' %}" class="btnListar"></a>
  </div>
{% endblock %}

Ucc/matriculas/templates/matriculas/login.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="es">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Matriculas - UCC</title>
  <!-- CSS  -->
  <link href="{% static 'matriculas/' %}css/bootstrap.min.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'matriculas/' %}css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body>
  <div class="section containerLogo">
    <div class="container">
      <br>
      <div class="login">
        <h1 class="header" align="center"></h1>
        <div class="row" align="center">
          <div class="login-container col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 col-lg-4 col-lg-offset-4">
            <form id="form-login" action="" method="post">
              {% csrf_token %}
              <div class="col-xs-12 form-group">
                  <img src="{% static 'matriculas/' %}img/logo-ucc.png" title="Catálogo" alt="">
              </div>
              <div class="col-xs-12">
                <div class="form-group">
                  <label for="">Usuario</label>
                  <input class="campo form-control" id="" name="username" type="text">
                </div>
              </div>
              <div class="col-xs-12 form-group">
                  <label for="">Contraseña</label>
                  <input class="campo form-control" id="" name="password" type="password">
              </div>
              <div class="col-xs-12 form-group">
                 <button type="submit" class="btn btn-generico waves-effect z-depth-3">INGRESAR</button>
                 <span></span>
              </div>
            </form>
            <div class="sheet"></div>
          </div><!-- login-container -->
        </div>
      </div><!-- LOGIN -->
    </div>
  </div>
  <!--  Scripts-->
  <script src="{% static 'matriculas/' %}js/jquery-2.1.1.min.js"></script>
  <script src="{% static 'matriculas/' %}js/bootstrap.min.js"></script>
  <script src="{% static 'matriculas/' %}js/init.js"></script>
  <script src="{% static 'matriculas/' %}js/pages/readyLogin.js"></script>
  <script>$(function(){ ReadyLogin.init(); });</script>
  </body>
</html>

Ucc/matriculas/templates/matriculas/realizar-matricula.html
{% extends 'matriculas/base.html' %}

{% block titulo %}
  <h2>Realizar matriculas - UCC</h2>
{% endblock %}
{% block contenido %}
  {% csrf_token %}
  <div style="margin-left:400px;">
    {{ form.as_p }}
  </div>
  <input type="submit" name="" value="Crear"  class="btn btn-generico" style="margin-left:410px;">
  <a href="{% url "index" %}"><button type="button"  class="btn btn-generico">Regresar</button></a>
{% endblock %}